Bk = {
	keyBk : {
		pressCode : {
			' ' :   32,
			'!'	: 	33,
			'"'	: 	34,
			'#'	: 	35,
			'$'	: 	36,
			'%'	: 	37,
			'&'	: 	38,
			"'"	: 	39,
			'('	: 	40,
			')'	: 	41,
			'*'	: 	42,
			'+'	: 	43,
			','	: 	44,
			'-'	: 	45,
			'.'	: 	46,
			'/'	: 	47,
			'{'	: 	123,
			'|'	: 	124,
			'}'	: 	125,
			'~'	: 	126,
			':'	: 	58,
			';'	: 	59,
			'<'	: 	60,
			'='	: 	61,
			'>'	: 	62,
			'?'	: 	63,
			'@'	: 	64,
			']'	: 	91,
			']'	: 	93,
			'^'	: 	94,
			'_'	: 	95,
			'`'	: 	96,
			0	: 	48,
			1	: 	49,
			2	: 	50,
			3	: 	51,
			4	: 	52,
			5	: 	53,
			6	: 	54,
			7	: 	55,
			8	: 	56,
			9	: 	57,
			A	: 	65,
			B	: 	66,
			C	: 	67,
			D	: 	68,
			E	: 	69,
			F	: 	70,
			G	: 	71,
			H	: 	72,
			I	: 	73,
			J	: 	74,
			K	: 	75,
			L	: 	76,
			M	: 	77,
			N	: 	78,
			O	: 	79,
			P	: 	80,
			Q	: 	81,
			R	: 	82,
			S	: 	83,
			T	: 	84,
			U	: 	85,
			V	: 	86,
			W	: 	87,
			X	: 	88,
			Y	: 	89,
			Z	: 	90,
			a	: 	97,
			b	: 	98,
			c	: 	99,
			d	: 	100,
			e	: 	101,
			f	: 	102,
			g	: 	103,
			h	: 	104,
			i	: 	105,
			j	: 	106,
			k	: 	107,
			l	: 	108,
			m	: 	109,
			n	: 	110,
			o	: 	111,
			p	: 	112,
			q	: 	113,
			r	: 	114,
			s	: 	115,
			t	: 	116,
			u	: 	117,
			v	: 	118,
			w	: 	119,
			x	: 	120,
			y	: 	121,
			z	: 	122,
		},
		defaultWords : [
			'there is no spoon', 
			'i see dead people', 
			'He is too old to work.',
			'This problem is too difficult for me to solve.',
			'He was never too great to do a kindness.',
			'He was too wise not to know it.',
			'Are you now strong enough to walk?',
			'He was kind enough to carry my baggage and show me the station.',
			'This boy is not old enough to go to school.',
			'To tell the truth, the lecture falls far short of my expectation.',
			'To begin with, he is healthy.',
			'To do him justice, we must admit that his intentions were good.',
			'To be frank with you, I cannot approve of your conduct.',
			'Strange to say, both shakespeare and Cervantes died on April 23, 1616.',
			'To do his best, he could not finish it.',
			'To make the matter worse, his child came down with malaria.',
			'To add to his difficulty, he became blind in one eye.',
			'To crown all, the movie was awarded Le GranePrix.',
			'He can speak German and French, to say nothing of English.',
			'Not to mention riches, even food cannot be obtained without efforts.',
			'He is, so to speak, a living dictionary.',
			'You had better take moderate exercise.',
			'Had I better consult the doctor after all?',
			'You had better have done it yourself.',
			'I had sooner die than consent to such a plan.',
			'I have never heard her sing.',
			'A pin might have been heard to drop.',
			'I saw with my own eyes a man enter my room.',
			'The house was felt to shake.',
			'Let him go to sea if he wants to.',
			'He let it be known to only a few people.',
			'They made him confess his guilt.',
			'I will have some one come and help me.',
			'We finally got her to sing.',
			'Bid him wait.',
			'Help me pack my things.',
			'A rolling stone gathers no moss.',
			'Who knows the comedians aching heart behind his smilling eyes?',
			'This box containing a lot of wonderful things belongs to him.',
			'The man talking with an American over there is Mr.Chin a diplomat.',
			'He is commander of an army consisting of 3,000 men.',
			'He makes it a rule to go hiking in spring and autumn every year.',
			'For a while I stood trembling.',
			'The boy came running towards me.',
			'I kept waiting for my friend at the station for half an hour.',
			'I went on working without looking aside.',
			'I have a lot of visitors coming on Sunday.',
			'I saw a car running at full speed.',
			'He kept me waiting for more than an hour.',
			'When I awoke, I found myself lying in a strange room.',
			'The teacher caught a student cheating during the examination.',
			'The dog watched a plate of meat being moved about in the kitchen.',
			'They set the bell ringing.',
			'Walking along the street, I happened to meet an old friend of mine.',
			'Having finished breakfast, we left home for school.',
			'Aware of the approaching danger, he at once made ready to escape.',
			'Living in a remote village, I seldom have visitors.',
			'Having finished my part of the work, I was free to go home.',
			'The policeman, seeing she was perfectly composed and sober, left her.',
			'Turning to the left, you will see the public hall.',
			'Admitting what you say, I am still in doubt whether it is right or wrong.',
			'Granting that he was drunk, that is no excuse for his conduct.',
			'Closing the door, she went out.',
			'My train starts at nine, arriving in Busan at about two.',
			'Night coming on, I started for home.',
			'It being cold, I stayed at home all day.',
			'There being no elevator, I had to climb the stairs.',
			'Weather permitting, I will take a country walk tomorrow.',
			'Other things being equal, I perfer this.',
			'He often shakes his head when speaking English.',
			'He lay still, his heart beating heavily.',
			'Speaking of novels about China, have you ever read The Good Earth by Pearl Buck?',
			'Judging from his appearance, he must be a Koren.',
			'Strictly speaking, he is not a scientist.',
			'Considering her age, she looks wonderfully young.',
			'The accused is not guilty till he is convicted.',
			'A spoken language is different from a written one.',
			'Do you know an American missionary named Johnson?',
			'Turn to the left, and you will find a stone house surrounded by peach trees.',
			'He looks satisfied.',
			'The building remained unburned.',
			'He got slightly hurt on the left arm.',
			'I have grown tired of this work.',
			'Soon I shall get used to this work.',
			'He went in high spirits, but returned discouraged.',
			'Once you set about your work, dont leave it undone.',
			'I should like to see glass made.',
			'Very often I heard him spoken ill of.'],
	}
}